package ru.ok.android;

import android.support.design.C0000R;
import android.support.v7.gridlayout.C0028R;
import android.support.v7.mediarouter.C0029R;
import android.support.v7.recyclerview.C0030R;
import com.google.android.gms.plus.C0157R;
import ru.mail.libverify.C0176R;

/* renamed from: ru.ok.android.R */
public final class C0206R {

    /* renamed from: ru.ok.android.R.styleable */
    public static final class styleable {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 26;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AdsAttrs;
        public static final int AdsAttrs_adSize = 0;
        public static final int AdsAttrs_adSizes = 1;
        public static final int AdsAttrs_adUnitId = 2;
        public static final int[] AlertDialog;
        public static final int AlertDialog_android_layout = 0;
        public static final int AlertDialog_buttonPanelSideLayout = 1;
        public static final int AlertDialog_listItemLayout = 5;
        public static final int AlertDialog_listLayout = 2;
        public static final int AlertDialog_multiChoiceItemLayout = 3;
        public static final int AlertDialog_singleChoiceItemLayout = 4;
        public static final int[] AlignChildren;
        public static final int AlignChildren_aligning = 1;
        public static final int AlignChildren_anchor = 0;
        public static final int[] AppBarLayout;
        public static final int[] AppBarLayout_LayoutParams;
        public static final int AppBarLayout_LayoutParams_layout_scrollFlags = 0;
        public static final int AppBarLayout_LayoutParams_layout_scrollInterpolator = 1;
        public static final int AppBarLayout_android_background = 0;
        public static final int AppBarLayout_elevation = 1;
        public static final int AppBarLayout_expanded = 2;
        public static final int[] AppCompatTextView;
        public static final int AppCompatTextView_android_textAppearance = 0;
        public static final int AppCompatTextView_textAllCaps = 1;
        public static final int[] AppPollRadioView;
        public static final int AppPollRadioView_checked = 0;
        public static final int AppPollRadioView_radio_text = 1;
        public static final int[] ArcLayout;
        public static final int ArcLayout_childSize = 2;
        public static final int ArcLayout_fromDegrees = 0;
        public static final int ArcLayout_toDegrees = 1;
        public static final int[] AspectRatioView;
        public static final int AspectRatioView_aspectRatio = 0;
        public static final int AspectRatioView_maxHeight = 1;
        public static final int AspectRatioView_maxWidth = 2;
        public static final int[] AsyncDraweeView;
        public static final int AsyncDraweeView_alphaAnimationDuration = 3;
        public static final int AsyncDraweeView_android_scaleType = 0;
        public static final int AsyncDraweeView_bottomLeftCornerRadius = 9;
        public static final int AsyncDraweeView_bottomRightCornerRadius = 8;
        public static final int AsyncDraweeView_emptyRes = 2;
        public static final int AsyncDraweeView_roundedMargin = 5;
        public static final int AsyncDraweeView_roundingType = 4;
        public static final int AsyncDraweeView_stubRes = 1;
        public static final int AsyncDraweeView_topLeftCornerRadius = 6;
        public static final int AsyncDraweeView_topRightCornerRadius = 7;
        public static final int[] AvatarImageView;
        public static final int AvatarImageView_avatarStrokeColor = 1;
        public static final int AvatarImageView_avatarStrokeWidth = 0;
        public static final int[] BubbleTextIcon;
        public static final int BubbleTextIcon_bubbleBg = 3;
        public static final int BubbleTextIcon_bubble_layout_gravity = 0;
        public static final int BubbleTextIcon_bubble_layout_margin = 5;
        public static final int BubbleTextIcon_bubble_layout_marginBottom = 9;
        public static final int BubbleTextIcon_bubble_layout_marginLeft = 6;
        public static final int BubbleTextIcon_bubble_layout_marginRight = 7;
        public static final int BubbleTextIcon_bubble_layout_marginTop = 8;
        public static final int BubbleTextIcon_bubble_textAppearance = 10;
        public static final int BubbleTextIcon_iconSrc = 1;
        public static final int BubbleTextIcon_iconSrcSelect = 2;
        public static final int BubbleTextIcon_icon_layout_margin = 4;
        public static final int[] CenterLockViewPager;
        public static final int CenterLockViewPager_leftOffset = 0;
        public static final int CenterLockViewPager_rightOffset = 1;
        public static final int[] CollapsingAppBarLayout_LayoutParams;
        public static final int CollapsingAppBarLayout_LayoutParams_layout_collapseMode = 0;
        public static final int f65xad49a364 = 1;
        public static final int[] CollapsingToolbarLayout;
        public static final int CollapsingToolbarLayout_collapsedTitleGravity = 11;
        public static final int CollapsingToolbarLayout_collapsedTitleTextAppearance = 7;
        public static final int CollapsingToolbarLayout_contentScrim = 8;
        public static final int CollapsingToolbarLayout_expandedTitleGravity = 12;
        public static final int CollapsingToolbarLayout_expandedTitleMargin = 1;
        public static final int CollapsingToolbarLayout_expandedTitleMarginBottom = 5;
        public static final int CollapsingToolbarLayout_expandedTitleMarginEnd = 4;
        public static final int CollapsingToolbarLayout_expandedTitleMarginStart = 2;
        public static final int CollapsingToolbarLayout_expandedTitleMarginTop = 3;
        public static final int CollapsingToolbarLayout_expandedTitleTextAppearance = 6;
        public static final int CollapsingToolbarLayout_statusBarScrim = 9;
        public static final int CollapsingToolbarLayout_title = 0;
        public static final int CollapsingToolbarLayout_titleEnabled = 13;
        public static final int CollapsingToolbarLayout_toolbarId = 10;
        public static final int[] CompoundButton;
        public static final int CompoundButton_android_button = 0;
        public static final int CompoundButton_buttonTint = 1;
        public static final int CompoundButton_buttonTintMode = 2;
        public static final int[] CoordinatorLayout;
        public static final int[] CoordinatorLayout_LayoutParams;
        public static final int CoordinatorLayout_LayoutParams_android_layout_gravity = 0;
        public static final int CoordinatorLayout_LayoutParams_layout_anchor = 2;
        public static final int CoordinatorLayout_LayoutParams_layout_anchorGravity = 4;
        public static final int CoordinatorLayout_LayoutParams_layout_behavior = 1;
        public static final int CoordinatorLayout_LayoutParams_layout_keyline = 3;
        public static final int CoordinatorLayout_keylines = 0;
        public static final int CoordinatorLayout_statusBarBackground = 1;
        public static final int[] CreateMessage;
        public static final int CreateMessage_odklHint = 0;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_arrowHeadLength = 4;
        public static final int DrawerArrowToggle_arrowShaftLength = 5;
        public static final int DrawerArrowToggle_barLength = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int[] EmojiTextView;
        public static final int EmojiTextView_emoji_enabled = 0;
        public static final int[] FeedContent;
        public static final int FeedContent_bottomDividerBg = 3;
        public static final int FeedContent_bottomPadding = 0;
        public static final int FeedContent_noDividersBg = 5;
        public static final int FeedContent_topBottomDividersBg = 4;
        public static final int FeedContent_topDividerBg = 2;
        public static final int FeedContent_topPadding = 1;
        public static final int[] FeedFooterView;
        public static final int FeedFooterView_commentsIcon = 0;
        public static final int FeedFooterView_layout = 2;
        public static final int FeedFooterView_shareIcon = 1;
        public static final int[] FeedHeaderView;
        public static final int FeedHeaderView_layout = 2;
        public static final int FeedHeaderView_layoutDebug = 0;
        public static final int FeedHeaderView_timeTextAppearance = 1;
        public static final int[] FeedMediaTopic;
        public static final int FeedMediaTopic_linkDescriptionTextAppearance = 5;
        public static final int FeedMediaTopic_linkLinkTextAppearance = 6;
        public static final int FeedMediaTopic_linkTitleTextAppearance = 4;
        public static final int FeedMediaTopic_maxDisplayedBlocks = 0;
        public static final int FeedMediaTopic_maxTextLengthInBlock = 1;
        public static final int FeedMediaTopic_maxTextLinesInBlock = 2;
        public static final int FeedMediaTopic_maxTracksInBlock = 3;
        public static final int FeedMediaTopic_photoNoCollage = 9;
        public static final int FeedMediaTopic_showMoreAtBottom = 8;
        public static final int FeedMediaTopic_textEditable = 7;
        public static final int[] FeedMessageSpanFormatter;
        public static final int FeedMessageSpanFormatter_actorTextAppearance = 0;
        public static final int FeedMessageSpanFormatter_messageTextAppearance = 1;
        public static final int FeedMessageSpanFormatter_targetAppTextAppearance = 4;
        public static final int FeedMessageSpanFormatter_targetGroupTextAppearance = 3;
        public static final int FeedMessageSpanFormatter_targetTextAppearance = 2;
        public static final int[] FloatingActionButton;
        public static final int FloatingActionButton_android_background = 0;
        public static final int FloatingActionButton_backgroundTint = 6;
        public static final int FloatingActionButton_backgroundTintMode = 7;
        public static final int FloatingActionButton_borderWidth = 5;
        public static final int FloatingActionButton_elevation = 1;
        public static final int FloatingActionButton_fabSize = 3;
        public static final int FloatingActionButton_pressedTranslationZ = 4;
        public static final int FloatingActionButton_rippleColor = 2;
        public static final int[] FlowLayout;
        public static final int[] FlowLayout_Layout;
        public static final int FlowLayout_Layout_android_layout_gravity = 0;
        public static final int FlowLayout_android_gravity = 0;
        public static final int[] FrameActionBarLayout;
        public static final int FrameActionBarLayout_android_actionBarStyle = 0;
        public static final int[] GenericDraweeView;
        public static final int GenericDraweeView_actualImageScaleType = 11;
        public static final int GenericDraweeView_backgroundImage = 12;
        public static final int GenericDraweeView_fadeDuration = 0;
        public static final int GenericDraweeView_failureImage = 6;
        public static final int GenericDraweeView_failureImageScaleType = 7;
        public static final int GenericDraweeView_overlayImage = 13;
        public static final int GenericDraweeView_placeholderImage = 2;
        public static final int GenericDraweeView_placeholderImageScaleType = 3;
        public static final int GenericDraweeView_pressedStateOverlayImage = 14;
        public static final int GenericDraweeView_progressBarAutoRotateInterval = 10;
        public static final int GenericDraweeView_progressBarImage = 8;
        public static final int GenericDraweeView_progressBarImageScaleType = 9;
        public static final int GenericDraweeView_retryImage = 4;
        public static final int GenericDraweeView_retryImageScaleType = 5;
        public static final int GenericDraweeView_roundAsCircle = 15;
        public static final int GenericDraweeView_roundBottomLeft = 20;
        public static final int GenericDraweeView_roundBottomRight = 19;
        public static final int GenericDraweeView_roundTopLeft = 17;
        public static final int GenericDraweeView_roundTopRight = 18;
        public static final int GenericDraweeView_roundWithOverlayColor = 21;
        public static final int GenericDraweeView_roundedCornerRadius = 16;
        public static final int GenericDraweeView_roundingBorderColor = 23;
        public static final int GenericDraweeView_roundingBorderWidth = 22;
        public static final int GenericDraweeView_viewAspectRatio = 1;
        public static final int[] GifTextureView;
        public static final int GifTextureView_gifSource = 0;
        public static final int GifTextureView_isOpaque = 1;
        public static final int[] GifView;
        public static final int GifView_freezesAnimation = 0;
        public static final int[] GridLayout;
        public static final int[] GridLayout_Layout;
        public static final int GridLayout_Layout_android_layout_height = 1;
        public static final int GridLayout_Layout_android_layout_margin = 2;
        public static final int GridLayout_Layout_android_layout_marginBottom = 6;
        public static final int GridLayout_Layout_android_layout_marginLeft = 3;
        public static final int GridLayout_Layout_android_layout_marginRight = 5;
        public static final int GridLayout_Layout_android_layout_marginTop = 4;
        public static final int GridLayout_Layout_android_layout_width = 0;
        public static final int GridLayout_Layout_layout_column = 10;
        public static final int GridLayout_Layout_layout_columnSpan = 11;
        public static final int GridLayout_Layout_layout_columnWeight = 12;
        public static final int GridLayout_Layout_layout_gravity = 13;
        public static final int GridLayout_Layout_layout_row = 7;
        public static final int GridLayout_Layout_layout_rowSpan = 8;
        public static final int GridLayout_Layout_layout_rowWeight = 9;
        public static final int GridLayout_alignmentMode = 4;
        public static final int GridLayout_columnCount = 2;
        public static final int GridLayout_columnOrderPreserved = 6;
        public static final int GridLayout_orientation = 0;
        public static final int GridLayout_rowCount = 1;
        public static final int GridLayout_rowOrderPreserved = 5;
        public static final int GridLayout_useDefaultMargins = 3;
        public static final int[] LikesView;
        public static final int LikesView_actionBg = 1;
        public static final int LikesView_klassIcon = 0;
        public static final int LikesView_layout = 2;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] LoadMoreView;
        public static final int LoadMoreView_layout = 1;
        public static final int LoadMoreView_list_orientation = 0;
        public static final int[] LoadingImageView;
        public static final int LoadingImageView_circleCrop = 2;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 0;
        public static final int[] MapAttrs;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_liteMode = 6;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 15;
        public static final int MapAttrs_uiRotateGestures = 8;
        public static final int MapAttrs_uiScrollGestures = 9;
        public static final int MapAttrs_uiTiltGestures = 10;
        public static final int MapAttrs_uiZoomControls = 11;
        public static final int MapAttrs_uiZoomGestures = 12;
        public static final int MapAttrs_useViewLifecycle = 13;
        public static final int MapAttrs_zOrderOnTop = 14;
        public static final int[] MediaComposerPanel;
        public static final int MediaComposerPanel_srcIcon = 0;
        public static final int[] MediaComposerView;
        public static final int[] MediaComposerView_Layout;
        public static final int MediaComposerView_Layout_layout_width_percents = 0;
        public static final int MediaComposerView_items_vspacing = 0;
        public static final int MediaComposerView_scale_to_insert_enabled = 2;
        public static final int MediaComposerView_show_item_action_icon = 3;
        public static final int MediaComposerView_swipe_to_dismiss_enabled = 1;
        public static final int[] MediaRouteButton;
        public static final int MediaRouteButton_android_minHeight = 1;
        public static final int MediaRouteButton_android_minWidth = 0;
        public static final int MediaRouteButton_externalRouteEnabledDrawable = 2;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int[] MessageDataView;
        public static final int MessageDataView_android_maxWidth = 0;
        public static final int MessageDataView_authorNameDrawableLeft = 1;
        public static final int MessageDataView_expandRepliedToMessage = 2;
        public static final int[] MultiUserAvatar;
        public static final int MultiUserAvatar_leafSize = 0;
        public static final int[] NavigationView;
        public static final int NavigationView_android_background = 0;
        public static final int NavigationView_android_fitsSystemWindows = 1;
        public static final int NavigationView_android_maxWidth = 2;
        public static final int NavigationView_elevation = 3;
        public static final int NavigationView_headerLayout = 9;
        public static final int NavigationView_itemBackground = 7;
        public static final int NavigationView_itemIconTint = 5;
        public static final int NavigationView_itemTextAppearance = 8;
        public static final int NavigationView_itemTextColor = 6;
        public static final int NavigationView_menu = 4;
        public static final int[] NetworkStatusView;
        public static final int NetworkStatusView_expandedHeight = 0;
        public static final int[] NotificationView;
        public static final int NotificationView_border_type = 0;
        public static final int NotificationView_isGray = 1;
        public static final int[] OkLargeTabletLayout;
        public static final int OkLargeTabletLayout_left_layout_weight = 0;
        public static final int OkLargeTabletLayout_right_layout_weight = 1;
        public static final int[] OkViewStub;
        public static final int OkViewStub_inflatedId = 0;
        public static final int OkViewStub_layout = 2;
        public static final int OkViewStub_useInflatedLp = 1;
        public static final int[] PagerSlidingTabStrip;
        public static final int[] PagerSlidingTabStripEmoji;
        public static final int PagerSlidingTabStripEmoji_dividerColor = 2;
        public static final int PagerSlidingTabStripEmoji_emojiTabBackground = 7;
        public static final int PagerSlidingTabStripEmoji_indicatorColor = 0;
        public static final int PagerSlidingTabStripEmoji_indicatorHeight = 3;
        public static final int PagerSlidingTabStripEmoji_pstsDividerPadding = 9;
        public static final int PagerSlidingTabStripEmoji_pstsTextAllCaps = 10;
        public static final int PagerSlidingTabStripEmoji_scrollOffset = 6;
        public static final int PagerSlidingTabStripEmoji_shouldExpand = 8;
        public static final int PagerSlidingTabStripEmoji_tabPaddingLeftRight = 5;
        public static final int PagerSlidingTabStripEmoji_underlineColor = 1;
        public static final int PagerSlidingTabStripEmoji_underlineHeight = 4;
        public static final int PagerSlidingTabStrip_pstsDividerColor = 2;
        public static final int PagerSlidingTabStrip_pstsDividerPadding2 = 9;
        public static final int PagerSlidingTabStrip_pstsIndicatorColor = 0;
        public static final int PagerSlidingTabStrip_pstsIndicatorHeight = 3;
        public static final int PagerSlidingTabStrip_pstsScrollOffset = 6;
        public static final int PagerSlidingTabStrip_pstsShouldExpand = 8;
        public static final int PagerSlidingTabStrip_pstsTabBackground = 7;
        public static final int PagerSlidingTabStrip_pstsTabPaddingLeftRight = 5;
        public static final int PagerSlidingTabStrip_pstsTextAllCaps2 = 10;
        public static final int PagerSlidingTabStrip_pstsUnderlineColor = 1;
        public static final int PagerSlidingTabStrip_pstsUnderlineHeight = 4;
        public static final int[] ParallaxScroll;
        public static final int ParallaxScroll_circular_parallax = 3;
        public static final int ParallaxScroll_inner_parallax_factor = 1;
        public static final int ParallaxScroll_parallax_factor = 0;
        public static final int ParallaxScroll_parallax_views_num = 2;
        public static final int[] PasswordEditText;
        public static final int PasswordEditText_android_hint = 0;
        public static final int PasswordEditText_editText_paddingLeft = 4;
        public static final int PasswordEditText_editText_paddingRight = 3;
        public static final int PasswordEditText_password_alwaysVisible = 1;
        public static final int PasswordEditText_password_gravity = 5;
        public static final int PasswordEditText_validatePassword = 2;
        public static final int[] PhotoRollView;
        public static final int PhotoRollView_android_background = 0;
        public static final int PhotoRollView_bottomTextColor = 2;
        public static final int PhotoRollView_closeIcon = 4;
        public static final int PhotoRollView_lockIcon = 3;
        public static final int PhotoRollView_upperTextColor = 1;
        public static final int[] PlayPauseView;
        public static final int PlayPauseView_animation_duration = 7;
        public static final int PlayPauseView_pause_color = 5;
        public static final int PlayPauseView_pause_element_height = 1;
        public static final int PlayPauseView_pause_element_width = 0;
        public static final int PlayPauseView_pause_elements_margin = 2;
        public static final int PlayPauseView_play_color = 6;
        public static final int PlayPauseView_play_element_width = 3;
        public static final int PlayPauseView_play_offset = 4;
        public static final int[] PlayingProgressButton;
        public static final int PlayingProgressButton_pausedColor = 1;
        public static final int PlayingProgressButton_playingColor = 0;
        public static final int PlayingProgressButton_remainingColor = 2;
        public static final int PlayingProgressButton_strokeWidth = 3;
        public static final int[] PlayingState;
        public static final int PlayingState_state_buffering = 1;
        public static final int PlayingState_state_playing = 0;
        public static final int[] PollAnswerLayout;
        public static final int PollAnswerLayout_layout = 0;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int[] ProfileButton;
        public static final int ProfileButton_android_textColor = 1;
        public static final int ProfileButton_android_textSize = 0;
        public static final int ProfileButton_image = 3;
        public static final int ProfileButton_layout = 4;
        public static final int ProfileButton_titleText = 2;
        public static final int[] ProfileButtonsLayout;
        public static final int ProfileButtonsLayout_maxOpenViews = 0;
        public static final int[] ProgressBarView;
        public static final int ProgressBarView_progressColor = 0;
        public static final int[] ProgressWheel;
        public static final int ProgressWheel_barAngle = 11;
        public static final int ProgressWheel_barColor = 3;
        public static final int ProgressWheel_barWidth = 10;
        public static final int ProgressWheel_circleColor = 8;
        public static final int ProgressWheel_delayMillis = 7;
        public static final int ProgressWheel_radius = 9;
        public static final int ProgressWheel_rimColor = 4;
        public static final int ProgressWheel_rimWidth = 5;
        public static final int ProgressWheel_spinSpeed = 6;
        public static final int ProgressWheel_text = 0;
        public static final int ProgressWheel_textColor = 1;
        public static final int ProgressWheel_textSize = 2;
        public static final int[] RecyclerView;
        public static final int RecyclerView_android_orientation = 0;
        public static final int RecyclerView_layoutManager = 1;
        public static final int RecyclerView_reverseLayout = 3;
        public static final int RecyclerView_spanCount = 2;
        public static final int RecyclerView_stackFromEnd = 4;
        public static final int[] RelativeLayoutMaxWidth;
        public static final int RelativeLayoutMaxWidth_android_maxWidth = 0;
        public static final int[] RelativeLayoutRounded;
        public static final int RelativeLayoutRounded_fillColor = 2;
        public static final int RelativeLayoutRounded_roundingType = 0;
        public static final int RelativeLayoutRounded_strokeColor = 1;
        public static final int RelativeLayoutRounded_strokeWidth = 3;
        public static final int[] ScrimInsetsFrameLayout;
        public static final int ScrimInsetsFrameLayout_insetForeground = 0;
        public static final int[] ScrollingViewBehavior_Params;
        public static final int ScrollingViewBehavior_Params_behavior_overlapTop = 0;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 8;
        public static final int SearchView_commitIcon = 13;
        public static final int SearchView_defaultQueryHint = 7;
        public static final int SearchView_goIcon = 9;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 15;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchHintIcon = 11;
        public static final int SearchView_searchIcon = 10;
        public static final int SearchView_submitBackground = 16;
        public static final int SearchView_suggestionRowLayout = 14;
        public static final int SearchView_voiceIcon = 12;
        public static final int[] SimpleUrlImageView;
        public static final int SimpleUrlImageView_android_maxWidth = 0;
        public static final int[] SlidingDrawer;
        public static final int SlidingDrawer_allowSingleTap = 2;
        public static final int SlidingDrawer_animateOnClick = 3;
        public static final int SlidingDrawer_bottomOffset = 0;
        public static final int SlidingDrawer_content = 5;
        public static final int SlidingDrawer_delimiter = 6;
        public static final int SlidingDrawer_handle = 4;
        public static final int SlidingDrawer_topOffset = 1;
        public static final int[] SlidingMenu;
        public static final int SlidingMenu_behindOffset = 3;
        public static final int SlidingMenu_behindScrollScale = 5;
        public static final int SlidingMenu_behindWidth = 4;
        public static final int SlidingMenu_fadeDegree = 11;
        public static final int SlidingMenu_fadeEnabled = 10;
        public static final int SlidingMenu_mode = 0;
        public static final int SlidingMenu_selectorDrawable = 13;
        public static final int SlidingMenu_selectorEnabled = 12;
        public static final int SlidingMenu_shadowDrawable = 8;
        public static final int SlidingMenu_shadowWidth = 9;
        public static final int SlidingMenu_touchModeAbove = 6;
        public static final int SlidingMenu_touchModeBehind = 7;
        public static final int SlidingMenu_viewAbove = 1;
        public static final int SlidingMenu_viewBehind = 2;
        public static final int[] SmartEmptyView;
        public static final int[] SmartEmptyViewAnimated;
        public static final int SmartEmptyViewAnimated_background_stroke_width = 3;
        public static final int SmartEmptyViewAnimated_buttonTextColor = 2;
        public static final int SmartEmptyViewAnimated_subTitleColor = 1;
        public static final int SmartEmptyViewAnimated_titleColor = 0;
        public static final int SmartEmptyView_emptyText = 2;
        public static final int SmartEmptyView_errorText = 0;
        public static final int SmartEmptyView_noInternetText = 3;
        public static final int SmartEmptyView_progressText = 1;
        public static final int[] SnackbarLayout;
        public static final int SnackbarLayout_android_maxWidth = 0;
        public static final int SnackbarLayout_elevation = 1;
        public static final int SnackbarLayout_maxActionInlineWidth = 2;
        public static final int[] Spinner;
        public static final int Spinner_android_dropDownWidth = 2;
        public static final int Spinner_android_popupBackground = 0;
        public static final int Spinner_android_prompt = 1;
        public static final int Spinner_popupTheme = 3;
        public static final int[] Stream;
        public static final int[] StreamMusicTrackBigView;
        public static final int StreamMusicTrackBigView_keepPlaylistImage = 0;
        public static final int[] StreamPhotoViewPager;
        public static final int StreamPhotoViewPager_leftOffset = 3;
        public static final int StreamPhotoViewPager_pageMargin = 0;
        public static final int StreamPhotoViewPager_pageWidthFactor = 1;
        public static final int StreamPhotoViewPager_rightOffset = 4;
        public static final int StreamPhotoViewPager_verticalPhotosSquared = 2;
        public static final int[] StreamScrollTopView;
        public static final int StreamScrollTopView_layout = 0;
        public static final int StreamScrollTopView_showCounter = 1;
        public static final int[] StreamTrackView;
        public static final int StreamTrackView_layout = 0;
        public static final int Stream_feedFooterStyle = 1;
        public static final int Stream_feedHeaderStyle = 0;
        public static final int Stream_photoPagerStyle = 2;
        public static final int[] SwitchCompat;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int[] TabLayout;
        public static final int TabLayout_tabBackground = 3;
        public static final int TabLayout_tabContentStart = 2;
        public static final int TabLayout_tabGravity = 5;
        public static final int TabLayout_tabIndicatorColor = 0;
        public static final int TabLayout_tabIndicatorHeight = 1;
        public static final int TabLayout_tabMaxWidth = 7;
        public static final int TabLayout_tabMinWidth = 6;
        public static final int TabLayout_tabMode = 4;
        public static final int TabLayout_tabPadding = 15;
        public static final int TabLayout_tabPaddingBottom = 14;
        public static final int TabLayout_tabPaddingEnd = 13;
        public static final int TabLayout_tabPaddingStart = 11;
        public static final int TabLayout_tabPaddingTop = 12;
        public static final int TabLayout_tabSelectedTextColor = 10;
        public static final int TabLayout_tabTextAppearance = 8;
        public static final int TabLayout_tabTextColor = 9;
        public static final int[] TextAppearance;
        public static final int TextAppearance_android_textColor = 3;
        public static final int TextAppearance_android_textSize = 0;
        public static final int TextAppearance_android_textStyle = 2;
        public static final int TextAppearance_android_typeface = 1;
        public static final int TextAppearance_textAllCaps = 4;
        public static final int[] TextInputLayout;
        public static final int TextInputLayout_android_hint = 1;
        public static final int TextInputLayout_android_textColorHint = 0;
        public static final int TextInputLayout_errorEnabled = 3;
        public static final int TextInputLayout_errorTextAppearance = 4;
        public static final int TextInputLayout_hintAnimationEnabled = 5;
        public static final int TextInputLayout_hintTextAppearance = 2;
        public static final int[] Theme;
        public static final int Theme_actionBarDivider = 23;
        public static final int Theme_actionBarItemBackground = 24;
        public static final int Theme_actionBarPopupTheme = 17;
        public static final int Theme_actionBarSize = 22;
        public static final int Theme_actionBarSplitStyle = 19;
        public static final int Theme_actionBarStyle = 18;
        public static final int Theme_actionBarTabBarStyle = 13;
        public static final int Theme_actionBarTabStyle = 12;
        public static final int Theme_actionBarTabTextStyle = 14;
        public static final int Theme_actionBarTheme = 20;
        public static final int Theme_actionBarWidgetTheme = 21;
        public static final int Theme_actionButtonStyle = 49;
        public static final int Theme_actionDropDownStyle = 45;
        public static final int Theme_actionMenuTextAppearance = 25;
        public static final int Theme_actionMenuTextColor = 26;
        public static final int Theme_actionModeBackground = 29;
        public static final int Theme_actionModeCloseButtonStyle = 28;
        public static final int Theme_actionModeCloseDrawable = 31;
        public static final int Theme_actionModeCopyDrawable = 33;
        public static final int Theme_actionModeCutDrawable = 32;
        public static final int Theme_actionModeFindDrawable = 37;
        public static final int Theme_actionModePasteDrawable = 34;
        public static final int Theme_actionModePopupWindowStyle = 39;
        public static final int Theme_actionModeSelectAllDrawable = 35;
        public static final int Theme_actionModeShareDrawable = 36;
        public static final int Theme_actionModeSplitBackground = 30;
        public static final int Theme_actionModeStyle = 27;
        public static final int Theme_actionModeWebSearchDrawable = 38;
        public static final int Theme_actionOverflowButtonStyle = 15;
        public static final int Theme_actionOverflowMenuStyle = 16;
        public static final int Theme_activityChooserViewStyle = 57;
        public static final int Theme_alertDialogButtonGroupStyle = 91;
        public static final int Theme_alertDialogCenterButtons = 92;
        public static final int Theme_alertDialogStyle = 90;
        public static final int Theme_alertDialogTheme = 93;
        public static final int Theme_android_windowAnimationStyle = 1;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_autoCompleteTextViewStyle = 98;
        public static final int Theme_borderlessButtonStyle = 54;
        public static final int Theme_buttonBarButtonStyle = 51;
        public static final int Theme_buttonBarNegativeButtonStyle = 96;
        public static final int Theme_buttonBarNeutralButtonStyle = 97;
        public static final int Theme_buttonBarPositiveButtonStyle = 95;
        public static final int Theme_buttonBarStyle = 50;
        public static final int Theme_buttonStyle = 99;
        public static final int Theme_buttonStyleSmall = 100;
        public static final int Theme_checkboxStyle = 101;
        public static final int Theme_checkedTextViewStyle = 102;
        public static final int Theme_colorAccent = 83;
        public static final int Theme_colorButtonNormal = 87;
        public static final int Theme_colorControlActivated = 85;
        public static final int Theme_colorControlHighlight = 86;
        public static final int Theme_colorControlNormal = 84;
        public static final int Theme_colorPrimary = 81;
        public static final int Theme_colorPrimaryDark = 82;
        public static final int Theme_colorSwitchThumbNormal = 88;
        public static final int Theme_controlBackground = 89;
        public static final int Theme_dialogPreferredPadding = 43;
        public static final int Theme_dialogTheme = 42;
        public static final int Theme_dividerHorizontal = 56;
        public static final int Theme_dividerVertical = 55;
        public static final int Theme_dropDownListViewStyle = 73;
        public static final int Theme_dropdownListPreferredItemHeight = 46;
        public static final int Theme_editTextBackground = 63;
        public static final int Theme_editTextColor = 62;
        public static final int Theme_editTextStyle = 103;
        public static final int Theme_homeAsUpIndicator = 48;
        public static final int Theme_listChoiceBackgroundIndicator = 80;
        public static final int Theme_listDividerAlertDialog = 44;
        public static final int Theme_listPopupWindowStyle = 74;
        public static final int Theme_listPreferredItemHeight = 68;
        public static final int Theme_listPreferredItemHeightLarge = 70;
        public static final int Theme_listPreferredItemHeightSmall = 69;
        public static final int Theme_listPreferredItemPaddingLeft = 71;
        public static final int Theme_listPreferredItemPaddingRight = 72;
        public static final int Theme_panelBackground = 77;
        public static final int Theme_panelMenuListTheme = 79;
        public static final int Theme_panelMenuListWidth = 78;
        public static final int Theme_popupMenuStyle = 60;
        public static final int Theme_popupWindowStyle = 61;
        public static final int Theme_radioButtonStyle = 104;
        public static final int Theme_ratingBarStyle = 105;
        public static final int Theme_searchViewStyle = 67;
        public static final int Theme_selectableItemBackground = 52;
        public static final int Theme_selectableItemBackgroundBorderless = 53;
        public static final int Theme_spinnerDropDownItemStyle = 47;
        public static final int Theme_spinnerStyle = 106;
        public static final int Theme_switchStyle = 107;
        public static final int Theme_textAppearanceLargePopupMenu = 40;
        public static final int Theme_textAppearanceListItem = 75;
        public static final int Theme_textAppearanceListItemSmall = 76;
        public static final int Theme_textAppearanceSearchResultSubtitle = 65;
        public static final int Theme_textAppearanceSearchResultTitle = 64;
        public static final int Theme_textAppearanceSmallPopupMenu = 41;
        public static final int Theme_textColorAlertDialogListItem = 94;
        public static final int Theme_textColorSearchUrl = 66;
        public static final int Theme_toolbarNavigationButtonStyle = 59;
        public static final int Theme_toolbarStyle = 58;
        public static final int Theme_windowActionBar = 2;
        public static final int Theme_windowActionBarOverlay = 4;
        public static final int Theme_windowActionModeOverlay = 5;
        public static final int Theme_windowFixedHeightMajor = 9;
        public static final int Theme_windowFixedHeightMinor = 7;
        public static final int Theme_windowFixedWidthMajor = 6;
        public static final int Theme_windowFixedWidthMinor = 8;
        public static final int Theme_windowMinWidthMajor = 10;
        public static final int Theme_windowMinWidthMinor = 11;
        public static final int Theme_windowNoTitle = 3;
        public static final int[] TitlePageIndicator;
        public static final int TitlePageIndicator_android_shadowColor = 2;
        public static final int TitlePageIndicator_android_shadowDx = 3;
        public static final int TitlePageIndicator_android_shadowDy = 4;
        public static final int TitlePageIndicator_android_shadowRadius = 5;
        public static final int TitlePageIndicator_android_textColor = 1;
        public static final int TitlePageIndicator_android_textSize = 0;
        public static final int TitlePageIndicator_centered = 17;
        public static final int TitlePageIndicator_clipPadding = 7;
        public static final int TitlePageIndicator_footerColor = 8;
        public static final int TitlePageIndicator_footerIndicatorHeight = 12;
        public static final int TitlePageIndicator_footerIndicatorStyle = 11;
        public static final int TitlePageIndicator_footerIndicatorUnderlinePadding = 13;
        public static final int TitlePageIndicator_footerLineColor = 9;
        public static final int TitlePageIndicator_footerLineHeight = 10;
        public static final int TitlePageIndicator_footerPadding = 14;
        public static final int TitlePageIndicator_selectedBold = 15;
        public static final int TitlePageIndicator_selectedColor = 18;
        public static final int TitlePageIndicator_strokeWidth = 19;
        public static final int TitlePageIndicator_titlePadding = 16;
        public static final int TitlePageIndicator_topPadding = 6;
        public static final int TitlePageIndicator_unselectedColor = 20;
        public static final int[] Toolbar;
        public static final int[] ToolbarMenuItem;
        public static final int ToolbarMenuItem_align = 1;
        public static final int ToolbarMenuItem_android_actionLayout = 0;
        public static final int[] ToolbarView;
        public static final int ToolbarView_menuResId = 0;
        public static final int ToolbarView_subMenuWithIcons = 1;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 19;
        public static final int Toolbar_collapseIcon = 18;
        public static final int Toolbar_contentInsetEnd = 6;
        public static final int Toolbar_contentInsetLeft = 7;
        public static final int Toolbar_contentInsetRight = 8;
        public static final int Toolbar_contentInsetStart = 5;
        public static final int Toolbar_logo = 4;
        public static final int Toolbar_logoDescription = 22;
        public static final int Toolbar_maxButtonHeight = 17;
        public static final int Toolbar_navigationContentDescription = 21;
        public static final int Toolbar_navigationIcon = 20;
        public static final int Toolbar_popupTheme = 9;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 11;
        public static final int Toolbar_subtitleTextColor = 24;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 16;
        public static final int Toolbar_titleMarginEnd = 14;
        public static final int Toolbar_titleMarginStart = 13;
        public static final int Toolbar_titleMarginTop = 15;
        public static final int Toolbar_titleMargins = 12;
        public static final int Toolbar_titleTextAppearance = 10;
        public static final int Toolbar_titleTextColor = 23;
        public static final int[] UpdateView;
        public static final int UpdateView_route = 0;
        public static final int[] UploadAvatarRoundedImageView;
        public static final int UploadAvatarRoundedImageView_femalePlaceHolder = 1;
        public static final int UploadAvatarRoundedImageView_malePlaceHolder = 0;
        public static final int UploadAvatarRoundedImageView_progressRadius = 3;
        public static final int UploadAvatarRoundedImageView_showHint = 2;
        public static final int[] VideoThumbView;
        public static final int VideoThumbView_aspectRatio = 0;
        public static final int VideoThumbView_layout = 1;
        public static final int[] View;
        public static final int[] ViewBackgroundHelper;
        public static final int ViewBackgroundHelper_android_background = 0;
        public static final int ViewBackgroundHelper_backgroundTint = 1;
        public static final int ViewBackgroundHelper_backgroundTintMode = 2;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 1;
        public static final int View_android_theme = 0;
        public static final int View_paddingEnd = 3;
        public static final int View_paddingStart = 2;
        public static final int View_theme = 4;

        static {
            ActionBar = new int[]{C0176R.attr.height, C0176R.attr.title, C0176R.attr.navigationMode, C0176R.attr.displayOptions, C0176R.attr.subtitle, C0176R.attr.titleTextStyle, C0176R.attr.subtitleTextStyle, C0176R.attr.icon, C0176R.attr.logo, C0176R.attr.divider, C0176R.attr.background, C0176R.attr.backgroundStacked, C0176R.attr.backgroundSplit, C0176R.attr.customNavigationLayout, C0176R.attr.homeLayout, C0176R.attr.progressBarStyle, C0176R.attr.indeterminateProgressStyle, C0176R.attr.progressBarPadding, C0176R.attr.itemPadding, C0176R.attr.hideOnContentScroll, C0176R.attr.contentInsetStart, C0176R.attr.contentInsetEnd, C0176R.attr.contentInsetLeft, C0176R.attr.contentInsetRight, C0176R.attr.elevation, C0176R.attr.popupTheme, C0176R.attr.homeAsUpIndicator};
            int[] iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[View_android_theme];
            ActionMode = new int[]{C0176R.attr.height, C0176R.attr.titleTextStyle, C0176R.attr.subtitleTextStyle, C0176R.attr.background, C0176R.attr.backgroundSplit, C0176R.attr.closeItemLayout};
            ActivityChooserView = new int[]{C0176R.attr.initialActivityCount, C0176R.attr.expandActivityOverflowButtonDrawable};
            AdsAttrs = new int[]{C0176R.attr.adSize, C0176R.attr.adSizes, C0176R.attr.adUnitId};
            AlertDialog = new int[]{16842994, C0176R.attr.buttonPanelSideLayout, C0176R.attr.listLayout, C0176R.attr.multiChoiceItemLayout, C0176R.attr.singleChoiceItemLayout, C0176R.attr.listItemLayout};
            AlignChildren = new int[]{2130772047, 2130772048};
            AppBarLayout = new int[]{16842964, C0176R.attr.elevation, C0000R.attr.expanded};
            AppBarLayout_LayoutParams = new int[]{C0000R.attr.layout_scrollFlags, C0000R.attr.layout_scrollInterpolator};
            AppCompatTextView = new int[]{16842804, C0176R.attr.textAllCaps};
            AppPollRadioView = new int[]{2130772053, 2130772054};
            ArcLayout = new int[]{2130772055, 2130772056, 2130772057};
            AspectRatioView = new int[]{2130772058, 2130772059, 2130772060};
            AsyncDraweeView = new int[]{16843037, 2130772061, 2130772062, 2130772063, 2130772064, 2130772065, 2130772066, 2130772067, 2130772068, 2130772069};
            AvatarImageView = new int[]{2130772070, 2130772071};
            BubbleTextIcon = new int[]{2130771970, 2130772072, 2130772073, 2130772074, 2130772075, 2130772076, 2130772077, 2130772078, 2130772079, 2130772080, 2130772081};
            CenterLockViewPager = new int[]{2130772359, 2130772360};
            CollapsingAppBarLayout_LayoutParams = new int[]{C0000R.attr.layout_collapseMode, C0000R.attr.layout_collapseParallaxMultiplier};
            CollapsingToolbarLayout = new int[]{C0176R.attr.title, C0000R.attr.expandedTitleMargin, C0000R.attr.expandedTitleMarginStart, C0000R.attr.expandedTitleMarginTop, C0000R.attr.expandedTitleMarginEnd, C0000R.attr.expandedTitleMarginBottom, C0000R.attr.expandedTitleTextAppearance, C0000R.attr.collapsedTitleTextAppearance, C0000R.attr.contentScrim, C0000R.attr.statusBarScrim, C0000R.attr.toolbarId, C0000R.attr.collapsedTitleGravity, C0000R.attr.expandedTitleGravity, C0000R.attr.titleEnabled};
            CompoundButton = new int[]{16843015, C0176R.attr.buttonTint, C0176R.attr.buttonTintMode};
            CoordinatorLayout = new int[]{C0000R.attr.keylines, C0000R.attr.statusBarBackground};
            CoordinatorLayout_LayoutParams = new int[]{16842931, C0000R.attr.layout_behavior, C0000R.attr.layout_anchor, C0000R.attr.layout_keyline, C0000R.attr.layout_anchorGravity};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772105;
            CreateMessage = iArr;
            DrawerArrowToggle = new int[]{C0176R.attr.color, C0176R.attr.spinBars, C0176R.attr.drawableSize, C0176R.attr.gapBetweenBars, C0176R.attr.arrowHeadLength, C0176R.attr.arrowShaftLength, C0176R.attr.barLength, C0176R.attr.thickness};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772114;
            EmojiTextView = iArr;
            FeedContent = new int[]{2130771969, 2130772010, 2130772115, 2130772116, 2130772117, 2130772118};
            FeedFooterView = new int[]{2130772119, 2130772120, C0176R.attr.layout};
            FeedHeaderView = new int[]{2130772121, 2130772122, C0176R.attr.layout};
            FeedMediaTopic = new int[]{2130772123, 2130772124, 2130772125, 2130772126, 2130772127, 2130772128, 2130772129, 2130772130, 2130772131, 2130772132};
            FeedMessageSpanFormatter = new int[]{2130772133, 2130772134, 2130772135, 2130772136, 2130772137};
            FloatingActionButton = new int[]{16842964, C0176R.attr.elevation, C0000R.attr.rippleColor, C0000R.attr.fabSize, C0000R.attr.pressedTranslationZ, C0000R.attr.borderWidth, C0176R.attr.backgroundTint, C0176R.attr.backgroundTintMode};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16842927;
            FlowLayout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16842931;
            FlowLayout_Layout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16843470;
            FrameActionBarLayout = iArr;
            GenericDraweeView = new int[]{2130772142, 2130772143, 2130772144, 2130772145, 2130772146, 2130772147, 2130772148, 2130772149, 2130772150, 2130772151, 2130772152, 2130772153, 2130772154, 2130772155, 2130772156, 2130772157, 2130772158, 2130772159, 2130772160, 2130772161, 2130772162, 2130772163, 2130772164, 2130772165};
            GifTextureView = new int[]{2130772166, 2130772167};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772168;
            GifView = iArr;
            GridLayout = new int[]{C0028R.attr.orientation, C0028R.attr.rowCount, C0028R.attr.columnCount, C0028R.attr.useDefaultMargins, C0028R.attr.alignmentMode, C0028R.attr.rowOrderPreserved, C0028R.attr.columnOrderPreserved};
            GridLayout_Layout = new int[]{16842996, 16842997, 16842998, 16842999, 16843000, 16843001, 16843002, C0028R.attr.layout_row, C0028R.attr.layout_rowSpan, C0028R.attr.layout_rowWeight, C0028R.attr.layout_column, C0028R.attr.layout_columnSpan, C0028R.attr.layout_columnWeight, C0028R.attr.layout_gravity};
            LikesView = new int[]{2130772183, 2130772184, C0176R.attr.layout};
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C0176R.attr.divider, C0176R.attr.measureWithLargestChild, C0176R.attr.showDividers, C0176R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            LoadMoreView = new int[]{2130772188, C0176R.attr.layout};
            LoadingImageView = new int[]{C0157R.attr.imageAspectRatioAdjust, C0157R.attr.imageAspectRatio, C0157R.attr.circleCrop};
            MapAttrs = new int[]{C0176R.attr.mapType, C0176R.attr.cameraBearing, C0176R.attr.cameraTargetLat, C0176R.attr.cameraTargetLng, C0176R.attr.cameraTilt, C0176R.attr.cameraZoom, C0157R.attr.liteMode, C0176R.attr.uiCompass, C0176R.attr.uiRotateGestures, C0176R.attr.uiScrollGestures, C0176R.attr.uiTiltGestures, C0176R.attr.uiZoomControls, C0176R.attr.uiZoomGestures, C0176R.attr.useViewLifecycle, C0176R.attr.zOrderOnTop, C0157R.attr.uiMapToolbar};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772208;
            MediaComposerPanel = iArr;
            MediaComposerView = new int[]{2130772209, 2130772210, 2130772211, 2130772212};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772213;
            MediaComposerView_Layout = iArr;
            MediaRouteButton = new int[]{16843071, 16843072, C0029R.attr.externalRouteEnabledDrawable};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C0176R.attr.showAsAction, C0176R.attr.actionLayout, C0176R.attr.actionViewClass, C0176R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C0176R.attr.preserveIconSpacing};
            MessageDataView = new int[]{16843039, 2130772220, 2130772221};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772222;
            MultiUserAvatar = iArr;
            NavigationView = new int[]{16842964, 16842973, 16843039, C0176R.attr.elevation, C0000R.attr.menu, C0000R.attr.itemIconTint, C0000R.attr.itemTextColor, C0000R.attr.itemBackground, C0000R.attr.itemTextAppearance, C0000R.attr.headerLayout};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772229;
            NetworkStatusView = iArr;
            NotificationView = new int[]{2130772230, 2130772231};
            OkLargeTabletLayout = new int[]{2130772232, 2130772233};
            OkViewStub = new int[]{2130772234, 2130772235, C0176R.attr.layout};
            PagerSlidingTabStrip = new int[]{2130772236, 2130772237, 2130772238, 2130772239, 2130772240, 2130772241, 2130772242, 2130772243, 2130772244, 2130772245, 2130772246};
            PagerSlidingTabStripEmoji = new int[]{2130772247, 2130772248, 2130772249, 2130772250, 2130772251, 2130772252, 2130772253, 2130772254, 2130772255, 2130772256, 2130772257};
            ParallaxScroll = new int[]{2130772258, 2130772259, 2130772260, 2130772261};
            PasswordEditText = new int[]{16843088, 2130772262, 2130772263, 2130772264, 2130772265, 2130772266};
            PhotoRollView = new int[]{16842964, 2130772267, 2130772268, 2130772269, C0176R.attr.closeIcon};
            PlayPauseView = new int[]{2130772270, 2130772271, 2130772272, 2130772273, 2130772274, 2130772275, 2130772276, 2130772277};
            PlayingProgressButton = new int[]{2130772278, 2130772279, 2130772280, 2130772507};
            PlayingState = new int[]{2130772281, 2130772282};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0176R.attr.layout;
            PollAnswerLayout = iArr;
            PopupWindow = new int[]{16843126, C0176R.attr.overlapAnchor};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0176R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            ProfileButton = new int[]{16842901, 16842904, 2130772285, 2130772286, C0176R.attr.layout};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772287;
            ProfileButtonsLayout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772288;
            ProgressBarView = iArr;
            ProgressWheel = new int[]{2130772289, 2130772290, 2130772291, 2130772292, 2130772293, 2130772294, 2130772295, 2130772296, 2130772297, 2130772298, 2130772299, 2130772300};
            RecyclerView = new int[]{16842948, C0030R.attr.layoutManager, C0030R.attr.spanCount, C0030R.attr.reverseLayout, C0030R.attr.stackFromEnd};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16843039;
            RelativeLayoutMaxWidth = iArr;
            RelativeLayoutRounded = new int[]{2130772064, 2130772305, 2130772306, 2130772507};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0000R.attr.insetForeground;
            ScrimInsetsFrameLayout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0000R.attr.behavior_overlapTop;
            ScrollingViewBehavior_Params = iArr;
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C0176R.attr.layout, C0176R.attr.iconifiedByDefault, C0176R.attr.queryHint, C0176R.attr.defaultQueryHint, C0176R.attr.closeIcon, C0176R.attr.goIcon, C0176R.attr.searchIcon, C0176R.attr.searchHintIcon, C0176R.attr.voiceIcon, C0176R.attr.commitIcon, C0176R.attr.suggestionRowLayout, C0176R.attr.queryBackground, C0176R.attr.submitBackground};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16843039;
            SimpleUrlImageView = iArr;
            SlidingDrawer = new int[]{2130772322, 2130772323, 2130772324, 2130772325, 2130772326, 2130772327, 2130772328};
            SlidingMenu = new int[]{2130772329, 2130772330, 2130772331, 2130772332, 2130772333, 2130772334, 2130772335, 2130772336, 2130772337, 2130772338, 2130772339, 2130772340, 2130772341, 2130772342};
            SmartEmptyView = new int[]{2130772343, 2130772344, 2130772345, 2130772346};
            SmartEmptyViewAnimated = new int[]{2130772347, 2130772348, 2130772349, 2130772350};
            SnackbarLayout = new int[]{16843039, C0176R.attr.elevation, C0000R.attr.maxActionInlineWidth};
            Spinner = new int[]{16843126, 16843131, 16843362, C0176R.attr.popupTheme};
            Stream = new int[]{2130772352, 2130772353, 2130772354};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772355;
            StreamMusicTrackBigView = iArr;
            StreamPhotoViewPager = new int[]{2130772356, 2130772357, 2130772358, 2130772359, 2130772360};
            StreamScrollTopView = new int[]{C0176R.attr.layout, 2130772361};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0176R.attr.layout;
            StreamTrackView = iArr;
            SwitchCompat = new int[]{16843044, 16843045, 16843074, C0176R.attr.track, C0176R.attr.thumbTextPadding, C0176R.attr.switchTextAppearance, C0176R.attr.switchMinWidth, C0176R.attr.switchPadding, C0176R.attr.splitTrack, C0176R.attr.showText};
            TabLayout = new int[]{C0000R.attr.tabIndicatorColor, C0000R.attr.tabIndicatorHeight, C0000R.attr.tabContentStart, C0000R.attr.tabBackground, C0000R.attr.tabMode, C0000R.attr.tabGravity, C0000R.attr.tabMinWidth, C0000R.attr.tabMaxWidth, C0000R.attr.tabTextAppearance, C0000R.attr.tabTextColor, C0000R.attr.tabSelectedTextColor, C0000R.attr.tabPaddingStart, C0000R.attr.tabPaddingTop, C0000R.attr.tabPaddingEnd, C0000R.attr.tabPaddingBottom, C0000R.attr.tabPadding};
            TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, C0176R.attr.textAllCaps};
            TextInputLayout = new int[]{16842906, 16843088, C0000R.attr.hintTextAppearance, C0000R.attr.errorEnabled, C0000R.attr.errorTextAppearance, C0000R.attr.hintAnimationEnabled};
            Theme = new int[]{16842839, 16842926, C0176R.attr.windowActionBar, C0176R.attr.windowNoTitle, C0176R.attr.windowActionBarOverlay, C0176R.attr.windowActionModeOverlay, C0176R.attr.windowFixedWidthMajor, C0176R.attr.windowFixedHeightMinor, C0176R.attr.windowFixedWidthMinor, C0176R.attr.windowFixedHeightMajor, C0176R.attr.windowMinWidthMajor, C0176R.attr.windowMinWidthMinor, C0176R.attr.actionBarTabStyle, C0176R.attr.actionBarTabBarStyle, C0176R.attr.actionBarTabTextStyle, C0176R.attr.actionOverflowButtonStyle, C0176R.attr.actionOverflowMenuStyle, C0176R.attr.actionBarPopupTheme, C0176R.attr.actionBarStyle, C0176R.attr.actionBarSplitStyle, C0176R.attr.actionBarTheme, C0176R.attr.actionBarWidgetTheme, C0176R.attr.actionBarSize, C0176R.attr.actionBarDivider, C0176R.attr.actionBarItemBackground, C0176R.attr.actionMenuTextAppearance, C0176R.attr.actionMenuTextColor, C0176R.attr.actionModeStyle, C0176R.attr.actionModeCloseButtonStyle, C0176R.attr.actionModeBackground, C0176R.attr.actionModeSplitBackground, C0176R.attr.actionModeCloseDrawable, C0176R.attr.actionModeCutDrawable, C0176R.attr.actionModeCopyDrawable, C0176R.attr.actionModePasteDrawable, C0176R.attr.actionModeSelectAllDrawable, C0176R.attr.actionModeShareDrawable, C0176R.attr.actionModeFindDrawable, C0176R.attr.actionModeWebSearchDrawable, C0176R.attr.actionModePopupWindowStyle, C0176R.attr.textAppearanceLargePopupMenu, C0176R.attr.textAppearanceSmallPopupMenu, C0176R.attr.dialogTheme, C0176R.attr.dialogPreferredPadding, C0176R.attr.listDividerAlertDialog, C0176R.attr.actionDropDownStyle, C0176R.attr.dropdownListPreferredItemHeight, C0176R.attr.spinnerDropDownItemStyle, C0176R.attr.homeAsUpIndicator, C0176R.attr.actionButtonStyle, C0176R.attr.buttonBarStyle, C0176R.attr.buttonBarButtonStyle, C0176R.attr.selectableItemBackground, C0176R.attr.selectableItemBackgroundBorderless, C0176R.attr.borderlessButtonStyle, C0176R.attr.dividerVertical, C0176R.attr.dividerHorizontal, C0176R.attr.activityChooserViewStyle, C0176R.attr.toolbarStyle, C0176R.attr.toolbarNavigationButtonStyle, C0176R.attr.popupMenuStyle, C0176R.attr.popupWindowStyle, C0176R.attr.editTextColor, C0176R.attr.editTextBackground, C0176R.attr.textAppearanceSearchResultTitle, C0176R.attr.textAppearanceSearchResultSubtitle, C0176R.attr.textColorSearchUrl, C0176R.attr.searchViewStyle, C0176R.attr.listPreferredItemHeight, C0176R.attr.listPreferredItemHeightSmall, C0176R.attr.listPreferredItemHeightLarge, C0176R.attr.listPreferredItemPaddingLeft, C0176R.attr.listPreferredItemPaddingRight, C0176R.attr.dropDownListViewStyle, C0176R.attr.listPopupWindowStyle, C0176R.attr.textAppearanceListItem, C0176R.attr.textAppearanceListItemSmall, C0176R.attr.panelBackground, C0176R.attr.panelMenuListWidth, C0176R.attr.panelMenuListTheme, C0176R.attr.listChoiceBackgroundIndicator, C0176R.attr.colorPrimary, C0176R.attr.colorPrimaryDark, C0176R.attr.colorAccent, C0176R.attr.colorControlNormal, C0176R.attr.colorControlActivated, C0176R.attr.colorControlHighlight, C0176R.attr.colorButtonNormal, C0176R.attr.colorSwitchThumbNormal, C0176R.attr.controlBackground, C0176R.attr.alertDialogStyle, C0176R.attr.alertDialogButtonGroupStyle, C0176R.attr.alertDialogCenterButtons, C0176R.attr.alertDialogTheme, C0176R.attr.textColorAlertDialogListItem, C0176R.attr.buttonBarPositiveButtonStyle, C0176R.attr.buttonBarNegativeButtonStyle, C0176R.attr.buttonBarNeutralButtonStyle, C0176R.attr.autoCompleteTextViewStyle, C0176R.attr.buttonStyle, C0176R.attr.buttonStyleSmall, C0176R.attr.checkboxStyle, C0176R.attr.checkedTextViewStyle, C0176R.attr.editTextStyle, C0176R.attr.radioButtonStyle, C0176R.attr.ratingBarStyle, C0176R.attr.spinnerStyle, C0176R.attr.switchStyle};
            TitlePageIndicator = new int[]{16842901, 16842904, 16843105, 16843106, 16843107, 16843108, 2130772010, 2130772495, 2130772496, 2130772497, 2130772498, 2130772499, 2130772500, 2130772501, 2130772502, 2130772503, 2130772504, 2130772505, 2130772506, 2130772507, 2130772508};
            Toolbar = new int[]{16842927, 16843072, C0176R.attr.title, C0176R.attr.subtitle, C0176R.attr.logo, C0176R.attr.contentInsetStart, C0176R.attr.contentInsetEnd, C0176R.attr.contentInsetLeft, C0176R.attr.contentInsetRight, C0176R.attr.popupTheme, C0176R.attr.titleTextAppearance, C0176R.attr.subtitleTextAppearance, C0176R.attr.titleMargins, C0176R.attr.titleMarginStart, C0176R.attr.titleMarginEnd, C0176R.attr.titleMarginTop, C0176R.attr.titleMarginBottom, C0176R.attr.maxButtonHeight, C0176R.attr.collapseIcon, C0176R.attr.collapseContentDescription, C0176R.attr.navigationIcon, C0176R.attr.navigationContentDescription, C0176R.attr.logoDescription, C0176R.attr.titleTextColor, C0176R.attr.subtitleTextColor};
            ToolbarMenuItem = new int[]{16843515, 2130772524};
            ToolbarView = new int[]{2130772525, 2130772526};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772527;
            UpdateView = iArr;
            UploadAvatarRoundedImageView = new int[]{2130772528, 2130772529, 2130772530, 2130772531};
            VideoThumbView = new int[]{2130772058, C0176R.attr.layout};
            View = new int[]{16842752, 16842970, C0176R.attr.paddingStart, C0176R.attr.paddingEnd, C0176R.attr.theme};
            ViewBackgroundHelper = new int[]{16842964, C0176R.attr.backgroundTint, C0176R.attr.backgroundTintMode};
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
        }
    }
}
